# Generated by Django 4.2 on 2025-05-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_featureusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('promptpay', 'PromptPay'), ('truemoney', 'TrueMoney'), ('linepay', 'LINE Pay')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('completed', 'สำเร็จ'), ('failed', 'ล้มเหลว'), ('refunded', 'คืนเงินแล้ว')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='myapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='QRCodePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('qr_string', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to='myapp.payment')),
            ],
        ),
    ]
